### PR TITLE
feat: implement Angular example

### PR DESCRIPTION
**Pull request by gioboa**
I replaced the dependencies with the official @module-federation/vite plugin.
It's working fine in `dev` and `preview` mode too.
Hope this helps, enjoy.

### CODE REVIEW

**Comment by Seifenn** [comment]
Hello @gioboa  i tested you example but i'm getting the following error when i launch the host application is there some other congfig that i need to do. It's the same old error code NG0203
image

**Comment by gioboa** [comment]
shared: ['@angular/core'] config is sharing the `@angular/core` so the NG0203 should disappear

**Comment by gioboa** [comment]
You can check [this example](https://github.com/gioboa/angular-microfrontend-demo) too. it's working fine.

**Comment by Seifenn** [comment]
I found a solution to the NG0203 .I replaced the package.lock with the package.lock of the example you sent and it works i dont get how the versions are different between the files when both projects have the same package.json

**Comment by gioboa** [comment]
Yep, that is odd. I'm glad you solved it

**Pull request merged**
